name: Pre release

on:
  push:
    branches: [ develop ]

jobs:
  pre-release:
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: latest
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: Release v${{ steps.version.outputs.version }}
          draft: true
          prerelease: false
